Revive project
Yupeek/Djrill pull request #1
Opened 2024-12-20 13:58 UTC by Keanel-19

Update the project to meet python 3 new standard.

- Static setup moved to pyproject.toml
- Remove python 2 support
- Fix bug in test suite introduced by python 3 new features
- Add tox config for test automation

Change to make :
- Replace travis config with new CI/CD app config

2025-01-06 07:19 UTC, seljin requested changes
small change

2025-01-06 07:19 UTC, seljin commented on README.rst
>  * Package on PyPI: https://pypi.python.org/pypi/djrill
tu peux remplacer par djrill-fork

2025-01-07 08:34 UTC, Keanel-19 commented
C’est publié : https://pypi.org/project/djrill-fork/

2025-11-06 15:26 UTC, seljin approved these changes
LGTM

2025-11-06 15:28 UTC, merged